import express from "express";
import { healthCheck } from "../controllers/healthController.js";
import productRoutes from "./productRoutes.js";
import authRoutes from "./authRoutes.js";
import catalogRoutes from "./catalogRoutes.js";
import inventoryRoutes from "./inventoryRoutes.js";
import salesRoutes from "./salesRoutes.js";
import auditRoutes from "./auditRoutes.js";
import branchRoutes from "./branchRoutes.js";
import invoiceImportRoutes from "./invoiceImportRoutes.js";
import offlineSyncRoutes from "./offlineSyncRoutes.js";
import tmdaQuarantineRoutes from "./tmdaQuarantineRoutes.js";
import financialRoutes from "./financialRoutes.js";
import complaintRoutes from "./complaintRoutes.js";
import universalCoreRoutes from "./universalCoreRoutes.js";
import pharmacyCompletionRoutes from "./pharmacyCompletionRoutes.js";
import delegationRoutes from "./delegationRoutes.js";
import accountingCompletionRoutes from "./accountingCompletionRoutes.js";

const router = express.Router();
router.get("/health", healthCheck);
router.use("/auth", authRoutes);
router.use("/products", productRoutes);
router.use("/catalog", catalogRoutes);
router.use(inventoryRoutes);
router.use(salesRoutes);
router.use(auditRoutes);
router.use(branchRoutes);
router.use("/invoices", invoiceImportRoutes);
router.use("/offline", offlineSyncRoutes);
router.use("/tmda", tmdaQuarantineRoutes);
router.use(financialRoutes);
router.use(complaintRoutes);
router.use(universalCoreRoutes);
router.use(pharmacyCompletionRoutes);
router.use("/delegations", delegationRoutes);
router.use(accountingCompletionRoutes);
export default router;
