import express from "express";
import { requireAuth, requireRole } from "../middleware/auth.js";
import { provisionTenant, transitionTenant, listTenantUsers, exportTenantSnapshot, validateRole } from "../services/tenantService.js";
import { upsertCustomer, upsertSupplier, listCustomers, listSuppliers } from "../services/customerSupplierService.js";
import { postJournal, listJournals } from "../services/ledgerPostingService.js";
import { queueNotification, listNotifications } from "../services/notificationService.js";
import { assertExportSafe } from "../services/migrationService.js";
import { recoveryPlan } from "../services/recoveryService.js";

const router = express.Router();
router.use(requireAuth);
router.get("/core/users", async (req,res,next)=>{ try { return res.json({success:true, users:await listTenantUsers({tenantId:req.user.tenantId, role:req.query.role ? validateRole(req.query.role) : undefined})}); } catch(e){next(e);} });
router.post("/core/tenants", requireRole("admin"), async (req,res,next)=>{ try { return res.status(201).json({success:true, tenant:await provisionTenant({...req.body, tenantId:req.body.tenantId || req.user.tenantId})}); } catch(e){next(e);} });
router.post("/core/tenants/:status", requireRole("admin"), async (req,res,next)=>{ try { return res.json({success:true, tenant:await transitionTenant({tenantId:req.user.tenantId,status:req.params.status,actorId:req.user.sub,reason:req.body.reason})}); } catch(e){next(e);} });
router.get("/core/export", requireRole("admin"), async (req,res,next)=>{ try { return res.json({success:true, export:assertExportSafe(await exportTenantSnapshot({tenantId:req.user.tenantId}))}); } catch(e){next(e);} });
router.get("/core/customers", async (req,res,next)=>{ try{return res.json({success:true,customers:await listCustomers({tenantId:req.user.tenantId})});}catch(e){next(e);} });
router.post("/core/customers", requireRole("admin","manager","staff"), async(req,res,next)=>{try{return res.status(201).json({success:true,customer:await upsertCustomer({...req.body,tenantId:req.user.tenantId})});}catch(e){next(e);}});
router.get("/core/suppliers", async (req,res,next)=>{ try{return res.json({success:true,suppliers:await listSuppliers({tenantId:req.user.tenantId})});}catch(e){next(e);} });
router.post("/core/suppliers", requireRole("admin","manager","staff"), async(req,res,next)=>{try{return res.status(201).json({success:true,supplier:await upsertSupplier({...req.body,tenantId:req.user.tenantId})});}catch(e){next(e);}});
router.get("/core/ledger", requireRole("admin","manager"), async(req,res,next)=>{try{return res.json({success:true,journals:await listJournals({tenantId:req.user.tenantId,account:req.query.account})});}catch(e){next(e);}});
router.post("/core/ledger", requireRole("admin","manager"), async(req,res,next)=>{try{return res.status(201).json({success:true,journal:await postJournal({...req.body,tenantId:req.user.tenantId})});}catch(e){next(e);}});
router.get("/core/notifications", async(req,res,next)=>{try{return res.json({success:true,notifications:await listNotifications({tenantId:req.user.tenantId,status:req.query.status})});}catch(e){next(e);}});
router.post("/core/notifications", requireRole("admin","manager"), async(req,res,next)=>{try{return res.status(201).json({success:true,notification:await queueNotification({...req.body,tenantId:req.user.tenantId})});}catch(e){next(e);}});
router.post("/core/recovery/plan", requireRole("admin"), (req,res,next)=>{try{return res.json({success:true,plan:recoveryPlan(req.body)});}catch(e){next(e);}});
export default router;
