import { getCollection } from "./index.js";
import { COLLECTIONS } from "../../shared/schemas/index.js";

function fail(message, statusCode = 400) { const e = new Error(message); e.statusCode = statusCode; throw e; }
function text(v) { return String(v ?? "").trim(); }
function id(v) { const value = text(v); if (!value) fail("Tenant context is required.", 403); return value; }
export async function upsertCustomer({ tenantId, customerId, name, phone, email, creditLimit, consent } = {}) { const t = id(tenantId); if (!text(name)) fail("Customer name is required."); const now = new Date(); const filter = { tenantId: t, customerId: text(customerId) || `CUS-${Date.now()}-${Math.random().toString(36).slice(2,8)}` }; const update = { $set: { tenantId: t, customerId: filter.customerId, name: text(name), phone: text(phone) || null, email: text(email) || null, creditLimit: creditLimit == null ? 0 : Number(creditLimit), consent: consent && typeof consent === "object" ? { ...consent } : {}, updatedAt: now }, $setOnInsert: { createdAt: now } }; const result = await getCollection(COLLECTIONS.CUSTOMERS).findOneAndUpdate(filter, update, { upsert: true, returnDocument: "after" }); return result.value; }
export async function upsertSupplier({ tenantId, supplierId, name, phone, email, terms } = {}) { const t = id(tenantId); if (!text(name)) fail("Supplier name is required."); const key = text(supplierId) || `SUP-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const now = new Date(); const result = await getCollection(COLLECTIONS.SUPPLIERS).findOneAndUpdate({ tenantId: t, supplierId: key }, { $set: { tenantId: t, supplierId: key, name: text(name), phone: text(phone) || null, email: text(email) || null, terms: terms && typeof terms === "object" ? { ...terms } : {}, updatedAt: now }, $setOnInsert: { createdAt: now } }, { upsert: true, returnDocument: "after" }); return result.value; }
export async function listCustomers({ tenantId, limit = 100 } = {}) { return getCollection(COLLECTIONS.CUSTOMERS).find({ tenantId: id(tenantId) }).sort({ name: 1 }).limit(Math.min(Math.max(Number(limit) || 100, 1), 200)).toArray(); }
export async function listSuppliers({ tenantId, limit = 100 } = {}) { return getCollection(COLLECTIONS.SUPPLIERS).find({ tenantId: id(tenantId) }).sort({ name: 1 }).limit(Math.min(Math.max(Number(limit) || 100, 1), 200)).toArray(); }
